# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dripemail', '0003_auto_20160518_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='dripbox',
            name='subscribe_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dripbox',
            name='success_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dripbox',
            name='unsubscribe_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='Subcription Confirmed'),
        ),
        migrations.AddField(
            model_name='lead',
            name='subscribed_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together=set([('email', 'dripbox')]),
        ),
    ]
