# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dripemail', '0004_auto_20160518_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lead Name'),
        ),
    ]
